---
remote_workdir: /tmp
local_workdir: /home/ljishen/workdir

benchmarks:
  - name: sysbench
    desc: "CPU performance test & Memory functions speed test"
    configs:
        # CPU performance test
      - desc: "CPU performance test: max-prime=20000"
        args: "--test=cpu --cpu-max-prime=20000 run"
        output_file_suffix: "cpu_20000.prof"
      - desc: "CPU performance test: max-prime=500000"
        args: "--test=cpu --cpu-max-prime=500000 run"
        output_file_suffix: "cpu_500000.prof"
      - desc: "CPU performance test: max-prime=1000000"
        args: "--test=cpu --cpu-max-prime=1000000 run"
        output_file_suffix: "cpu_1000000.prof"

        # Memory functions speed test
      - desc: "Memory functions speed test: memory-oper=read, memory-access-mode=seq"
        args: "--test=memory --memory-oper=read --memory-access-mode=seq run"
        output_file_suffix: "memory_read_seq.prof"
      - desc: "Memory functions speed test: memory-oper=write, memory-access-mode=seq"
        args: "--test=memory --memory-oper=write --memory-access-mode=seq run"
        output_file_suffix: "memory_write_seq.prof"
      - desc: "Memory functions speed test: memory-oper=read, memory-access-mode=rnd"
        args: "--test=memory --memory-oper=read --memory-access-mode=rnd run"
        output_file_suffix: "memory_read_rnd.prof"
      - desc: "Memory functions speed test: memory-oper=write, memory-access-mode=rnd"
        args: "--test=memory --memory-oper=write --memory-access-mode=rnd run"
        output_file_suffix: "memory_write_rnd.prof"
