---
- name: check number of hosts
  fail: msg="Need to specify at least two hosts for the parsing"
  when: (groups['all'] | length | int) < 2

- name: lookup base host
  include: lookup_base_host.yml
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: check_host

- name: check base host
  fail: msg="Please set attribute "base=True" to one of the hosts in the inventory file"
  when: base_host is undefined

- name: find all benchmarks profile folders
  find:
    file_type: directory
    paths: "{{ local_profs_dir }}"
  register: find_benchmark_folders_out

- name: ensure result folder exists
  file:
    path: "{{ local_res_file | dirname }}"
    state: directory

- name: remove old result file
  file:
    path: "{{ local_res_file }}"
    state: absent

- name: parse profiles by benchmark
  include: parse_by_benchmark.yml
  with_items: "{{ find_benchmark_folders_out.files }}"
  loop_control:
    loop_var: folder
