---
- name: get benchmark name
  set_fact: benchmark_name="{{ folder.path | basename }}"

- name: install basic package
  package:
    name: gnuplot
    state: latest
  become: yes
  when: benchmark_name == "pmbw"

- name: ({{ benchmark_name }}) parse profiles by host
  include: parse_by_host.yml 
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: cur_host
  when: cur_host != base_host
