---
# bench role will first use this configuration file for benchmarks if exists.
# This file is useful for testing individual benchmark cases.
# Here is an example.

benchmarks:
  - name: sysbench
    desc: "CPU & Memory & File I/O performance test"
    docker_image: ljishen/sysbench
    configs:
      # Memory functions speed test
      - desc: "Memory functions speed test: memory-block-size=1K, memory-oper=read, memory-access-mode=seq, max-time=300, max-requests=0 num-threads=2"
        args:
          run: "##OUTPUT_FILE## --test=memory --memory-block-size=1K --memory-oper=read --memory-access-mode=seq --max-time=300 --max-requests=0 --num-threads=2 run"
          docker_run: "-v `pwd`:/root/results ##CONTAINER_ID## /root/results/##OUTPUT_FILE## --test=memory --memory-block-size=1K --memory-oper=read --memory-access-mode=seq --max-time=300 --max-requests=0 --num-threads=2 run"
        output_file_suffix: "memory_1k_read_seq_time_300sec_threads_2.prof"
      - desc: "Memory functions speed test: memory-block-size=1K, memory-oper=write, memory-access-mode=seq, max-time=300, max-requests=0, num-threads=2"
        args:
          run: "##OUTPUT_FILE## --test=memory --memory-block-size=1K --memory-oper=write --memory-access-mode=seq --max-time=300 --max-requests=0 --num-threads=2 run"
          docker_run: "-v `pwd`:/root/results ##CONTAINER_ID## /root/results/##OUTPUT_FILE## --test=memory --memory-block-size=1K --memory-oper=write --memory-access-mode=seq --max-time=300 --max-requests=0 --num-threads=2 run"
        output_file_suffix: "memory_1k_write_seq_time_300sec_threads_2.prof"
      - desc: "Memory functions speed test: memory-block-size=1K, memory-oper=read, memory-access-mode=rnd, max-time=300, max-requests=0, num-threads=2"
        args:
          run: "##OUTPUT_FILE## --test=memory --memory-block-size=1K --memory-oper=read --memory-access-mode=rnd --max-time=300 --max-requests=0 --num-threads=2 run"
          docker_run: "-v `pwd`:/root/results ##CONTAINER_ID## /root/results/##OUTPUT_FILE## --test=memory --memory-block-size=1K --memory-oper=read --memory-access-mode=rnd --max-time=300 --max-requests=0 --num-threads=2 run"
        output_file_suffix: "memory_1k_read_rnd_time_300sec_threads_2.prof"
      - desc: "Memory functions speed test: memory-block-size=1K, memory-oper=write, memory-access-mode=rnd, max-time=300, max-requests=0, num-threads=2"
        args:
          run: "##OUTPUT_FILE## --test=memory --memory-block-size=1K, --memory-oper=write --memory-access-mode=rnd --max-time=300 --max-requests=0 --num-threads=2 run"
          docker_run: "-v `pwd`:/root/results ##CONTAINER_ID## /root/results/##OUTPUT_FILE## --test=memory --memory-block-size=1K --memory-oper=write --memory-access-mode=rnd --max-time=300 --max-requests=0 --num-threads=2 run"
        output_file_suffix: "memory_1k_write_rnd_time_300sec_threads_2.prof"
