---
# bench role will first use this configuration file for benchmarks if exists.
# This file is useful for testing individual benchmark cases.
# Here is an example.

benchmarks:
  - name: sysbench
    desc: "CPU & Memory & File I/O performance test"
    docker_image: ljishen/sysbench
    configs:
      # File I/O test
      - desc: "File I/O test: file preparation - file-num=128, file-total-size=4G"
        args:
          run: "##OUTPUT_FILE## --test=fileio --file-num=128 --file-total-size=4G prepare"
          docker_run: "-v `pwd`:/root/results -v `pwd`/workdir:/root/workdir ##CONTAINER_ID## /root/results/##OUTPUT_FILE## --test=fileio --file-num=128 --file-total-size=4G prepare"
        output_file_suffix: "fileio_prepare_ssd_num_128_size_4g.log"
      - desc: "File I/O test: run - file-num=128, file-total-size=4G, file-block-size=4K, max-time=240, max-requests=0, num-threads=1, file-test-mode=rndwr, file-extra-flags={sync,direct}"
        args:
          run: "##OUTPUT_FILE## --test=fileio --file-num=128 --file-total-size=4G --file-block-size=4K --max-time=240 --max-requests=0 --num-threads=1 --file-test-mode=rndwr --file-extra-flags={sync,direct} run"
          docker_run: "-v `pwd`:/root/results -v `pwd`/workdir:/root/workdir ##CONTAINER_ID## /root/results/##OUTPUT_FILE## --test=fileio --file-num=128 --file-total-size=4G --file-block-size=4K --max-time=240 --max-requests=0 --num-threads=1 --file-test-mode=rndwr --file-extra-flags={sync,direct} run"
        output_file_suffix: "fileio_run_ssd_num_128_size_4g_block_4k_time_240sec_1_thread_rndwr.prof"
      - desc: "File I/O test: file cleanup"
        args:
          run: "##OUTPUT_FILE## --test=fileio cleanup"
          docker_run: "-v `pwd`:/root/results -v `pwd`/workdir:/root/workdir ##CONTAINER_ID## /root/results/##OUTPUT_FILE## --test=fileio cleanup"
        output_file_suffix: "fileio_cleanup.log"
