---
- name: find benchmark configurations
  include_vars: "{{ item }}"
  with_first_found:
   - "bench_configs.yml"
   - "bench_configs_default.yml"

- name: loop all benchmarks
  include: run_benchmark.yml
  with_items: "{{ benchmarks }}"
  loop_control:
    loop_var: benchmark
  when: not ( benchmark.skip | default(False) )

- name: clean remote workdir
  file:
    path: "{{ remote_workdir }}"
    state: absent
  become: True
  when: clean_workdir
