---
- name: save the loops value for item
  set_fact: benchmark={{ item }}

- name: ensure script folder exists
  file:
    path: "{{ remote_workdir }}/{{ benchmark.name }}"
    state: directory

- name: copy run.sh script to remote location
  copy:
    dest: "{{ remote_workdir }}/{{ benchmark.name }}/run.sh"
    force: yes
    mode: 0755
    src: ../suite/{{ benchmark.name }}/run.sh 

- name: testAAA#
  debug: msg="{{ item }}"
  with_items: "{{ benchmark.configs }}"

- name: run {{ item.desc }}
  include: run_specific.yml item={{ item }}
  with_items: "{{ benchmark.configs }}"

- name: clean remote workdir
  file:
    path: "{{ remote_workdir }}/{{ benchmark.name }}"
    state: absent
