---
- name: set output file name
  set_fact: output_file_name=without_{{ inventory_hostname }}_{{ config.output_file_suffix }}

- name: run {{ config.desc }}
  shell: yes | ./run.sh {{ output_file_name }} {{ config.args }}
  args:
    chdir: "{{ remote_workdir }}/{{ benchmark.name }}"
  environment:
    PATH: /usr/local/bin:/usr/bin:/bin

- name: collect output profile
  fetch:
    dest: "{{ local_workdir }}/{{ benchmark.name }}"
    fail_on_missing: yes
    src: "{{ remote_workdir }}/{{ benchmark.name }}/{{ output_file_name }}"
