---
- name: run benchmark
  hosts: all
  gather_facts: false
  roles:
    - bench

- name: parse benchmark result profiles
  hosts: localhost
  roles:
    - parse

- name: launch IPython notebook server
  hosts: localhost
  gather_facts: false
  roles:
    - show
