---
- name: launch scipy-notebook container
  docker_container:
    detach: True
    image: "jupyter/scipy-notebook"
    name: "{{ notebook_container_name }}"
    published_ports:
      - "{{ container_public_port }}:8888"
    pull: true
    restart: yes
    force_kill: yes
    restart_policy: on-failure
    state: started
    volumes:
      - "{{ playbook_dir }}:/home/jovyan/work:rw"
